---

- name: Power on the bootstrap node
  delegate_to: localhost
  theforeman.foreman.host_power:
    server_url: "{{ sat_server }}"
    username: "{{ sat_username }}"
    password: "{{ sat_password }}"
    validate_certs: "{{ sat_ssl_enabled }}"
    name: "{{ item.name }}.{{ sat_domain }}"
    state: on
  with_items:
    - '{{ openshift_bootstrap }}'
  when:
    (openshift_bootstrap is defined) and
    (openshift_bootstrap | length > 0) and
    (sat_start_build | bool)
  tags:
    - create_host

- name: Power on the master nodes
  delegate_to: localhost
  theforeman.foreman.host_power:
    server_url: "{{ sat_server }}"
    username: "{{ sat_username }}"
    password: "{{ sat_password }}"
    validate_certs: "{{ sat_ssl_enabled }}"
    name: "{{ item.name }}.{{ sat_domain }}"
    state: on
  with_items:
    - '{{ openshift_masters }}'
  when:
    (openshift_masters is defined) and
    (openshift_masters | length > 0) and
    (sat_start_build | bool)
  tags:
    - create_host

- name: Power on the worker nodes
  delegate_to: localhost
  theforeman.foreman.host_power:
    server_url: "{{ sat_server }}"
    username: "{{ sat_username }}"
    password: "{{ sat_password }}"
    validate_certs: "{{ sat_ssl_enabled }}"
    name: "{{ item.name }}.{{ sat_domain }}"
    state: on
  with_items:
    - '{{ openshift_workers }}'
  when:
    (openshift_workers is defined) and
    (openshift_workers | length > 0) and
    (sat_start_build | bool)
  tags:
    - create_host
